apiVersion: v1
kind: Service
metadata:
  name: sigres-dm-service
  namespace: dev
spec:
  selector:
    app: sigres-dm
  ports:
    - name: admin
      protocol: TCP
      port: 7001
      nodePort: 30001
      targetPort: 7001
    - name: server-1
      protocol: TCP
      port: 7010
      nodePort: 30010
      targetPort: 7010
    - name: server-2
      protocol: TCP
      port: 7020
      nodePort: 30020
      targetPort: 7020
  type: NodePort